# Dependencies
```{r}
box::use(src / dirs[dirs])
box::use(src / compute[log10_floor, dec_places, spat_condeffs])
box::use(src / plot[settheme, plot_ticks, expand_rast, ])
box::use(readr[read_csv])
box::use(brms[...])
box::use(magrittr[`%>%`])
box::use(ggplot2[...])
box::use(dplyr)
box::use(terra)
box::use(sf)
box::use(ggtext)
box::use(patchwork[...])
```
# Import data

```{r}

ggplot(data = nestbox_df, aes(x = x, y = y, colour = northness)) +
    geom_point()
# Nestbox information
nestbox_df <- read_csv(file.path(dirs$resources, "nestbox_data.csv")) %>%
    janitor::clean_names()

# Breeding data*
breeding_df <- read_csv(file.path(dirs$data, "breeding_data.csv")) %>%
    dplyr::mutate(box = toupper(box)) %>%
    dplyr::left_join(nestbox_df, by = "box")

# Woodland contour (with gaps)
perimeter <- terra::vect(file.path(
    dirs$resources, "ww_contour", "wytham_perimeter.shp"
))
terra::crs(perimeter) <- "epsg:27700"

# *This only goes up to 2013, don't ask me why
```


# Models

## Formulae
```{r}

# I'll use default priors since this is just a minimal example

# For info on approximate gaussian process, choice of basis functions, etc,
# see https://arxiv.org/abs/2004.11408

# if you have a lot more data, fit a spline-based smooth
# [e.g., s(x,y, by=year)] instead

# Spatial distribution of lay dates (1 year only)
m_0_f <- brms::brmsformula(
    laydate ~ 1 + year + gp(x, y, k = 20, scale = TRUE, c = 5 / 4),
    family = gaussian()
)

# Spatial distribution of northness
m_1_f <- brms::brmsformula(
    northness ~ 1 + gp(x, y, k = 20, scale = TRUE, c = 5 / 4),
    family = gaussian()
)
```

## Fit

```{r}
m_0 <-
    brm(
        formula = m_0_f,
        data = breeding_df %>% filter(year == 2011),
        # prior = priors,
        iter = 2000, warmup = 500,
        chains = 4,
        cores = parallel::detectCores() - 1,
        seed = 444,
        sample_prior = FALSE,
        file = file.path(dirs$model_fits, "m_0"),
        file_refit = "on_change",
        backend = "cmdstanr",
        # comment out the 'backend' arg. if you don't
        # want to install cmdstanr (sampling will be slower)
        control = list(
            adapt_delta = 0.9,
            max_treedepth = 10
        )
    )

m_1 <-
    brm(
        formula = m_1_f,
        data = nestbox_df,
        # prior = priors,
        iter = 2000, warmup = 500,
        chains = 4,
        cores = parallel::detectCores() - 1,
        seed = 444,
        sample_prior = FALSE,
        file = file.path(dirs$model_fits, "m_1"),
        file_refit = "on_change",
        backend = "cmdstanr",
        # comment out the 'backend' arg. if you don't
        # want to install cmdstanr (sampling will be slower)
        control = list(
            adapt_delta = 0.9,
            max_treedepth = 10
        )
    )
```

# Plot model outcomes

```{r plot-settings}
# Plot settings

psetts <- list(
    text.colour = "#f2f2f2",
    background.colour = "#262626", # "transparent"
    text.size = 10
)
```

## Plot: mean lay date estimates + their standard errors

### Get estimates from fitted model

```{r}
# 1. Extract conditional effects
# Build and tweak your plot with low resolution (<100),
# then increase before you export the final version (~500)
m_0_df <- spat_condeffs(
    m_0,
    varnames = "x:y",
    resolution = 500,
    ndraws = 500
)

# 2. Expand and mask
m_0_expdf <- expand_rast(m_0_df)

masked_rast <- terra::rast(m_0_expdf, type = "xyz") %>%
    terra::mask(., perimeter) %>%
    terra::as.data.frame(xy = TRUE) %>%
    tibble::as_tibble()
```


### Plot estimates
```{r }
# Plot estimate

#' @param plot_type One of ('estimate', 'se')
plot_type <- "estimate"

ggplot2::ggplot() +
    ggplot2::geom_raster(
        data = masked_rast, aes(x = x, y = y, fill = !!sym(plot_type))
    ) +
    ggplot2::geom_sf(
        data = sf::st_as_sf(perimeter), fill = NA,
        size = 0.5,
        colour = psetts$text.colour
    ) +
    scale_size_continuous(range = c(0.5, 5)) +
    scale_fill_distiller(
        palette = "RdBu",
        name = ("Estimate\n(april day)\n"),
        breaks = plot_ticks(plot_type, masked_rast, 5),
        direction = 1,
        guide = guide_colorbar(
            ticks = FALSE,
            frame.colour = psetts$text.colour,
            frame.linewidth = 1.5,
            nbin = 1000
        )
    ) +
    settheme(
        text.size = psetts$text.size,
        text.colour = psetts$text.colour,
        back.fill = psetts$background.colour
    ) +
    labs(
        x = NULL,
        y = NULL,
        title = "Estimates of first egg date across space",
        subtitle = "*Posterior conditional effects of spatial predictor (GP)*<br>"
    ) -> laydate_estimate
```

### Plot SE of estimate
```{r }

#' @param plot_type One of ('estimate', 'se')
plot_type <- "se"

ggplot2::ggplot() +
    ggplot2::geom_raster(
        data = masked_rast, aes(x = x, y = y, fill = !!sym(plot_type))
    ) +
    ggplot2::geom_sf(
        data = sf::st_as_sf(perimeter), fill = NA,
        size = 0.5,
        colour = psetts$text.colour
    ) +
    scale_size_continuous(range = c(0.5, 5)) +
    scale_fill_distiller(
        palette = "RdBu",
        name = ("Standard error\nof estimate\n"),
        breaks = plot_ticks(plot_type, masked_rast, 5),
        direction = -1,
        guide = guide_colorbar(
            ticks = FALSE,
            frame.colour = psetts$text.colour,
            frame.linewidth = 1.5,
            nbin = 1000
        )
    ) +
    settheme(
        text.size = psetts$text.size,
        text.colour = psetts$text.colour,
        back.fill = psetts$background.colour
    ) +
    labs(
        x = NULL,
        y = NULL,
        title = "Standard errors of estimate",
        subtitle = "*Posterior conditional effects of spatial predictor*<br>"
    ) -> laydate_se
```

### Combine and save
```{r}

laydate_estimate_se <- (laydate_estimate + laydate_se) &
    theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    )
ggsave(
    filename = "laydate_estimate_se.png",
    plot = laydate_estimate_se,
    path = dirs$figs,
    scale = 1,
    width = 26,
    height = 13,
    units = "cm",
    dpi = 350,
    limitsize = FALSE,
    bg = "transparent"
)
```


## Plot: northness

### Get estimates from fitted model

```{r}
# 1. Extract conditional effects
# Build and tweak your plot with low resolution (<100),
# then increase before you export the final version (~500)
m_1_df <- spat_condeffs(
    m_1,
    varnames = "x:y",
    resolution = 300,
    ndraws = 500
)

# 2. Expand and mask
m_1_expdf <- expand_rast(m_1_df)

masked_rast <- terra::rast(m_1_expdf, type = "xyz") %>%
    terra::mask(., perimeter) %>%
    terra::as.data.frame(xy = TRUE) %>%
    tibble::as_tibble()
```


### Plot estimates
```{r }

#' @param plot_type One of ('estimate', 'se')
plot_type <- "estimate"

ggplot2::ggplot() +
    ggplot2::geom_raster(
        data = masked_rast, aes(x = x, y = y, fill = !!sym(plot_type))
    ) +
    ggplot2::geom_sf(
        data = sf::st_as_sf(perimeter), fill = NA,
        size = 0.3,
        colour = psetts$text.colour
    ) +
    scale_size_continuous(range = c(0.5, 5)) +
    scale_fill_viridis_c(
        option = "inferno",
        alpha = 1,
        direction = -1,
        name = "Northness",
        breaks = plot_ticks(plot_type, masked_rast, 5),
        guide = guide_colorbar(
            ticks = FALSE,
            frame.colour = psetts$text.colour,
            frame.linewidth = 1,
            nbin = 1000
        )
    ) +
    settheme(
        text.size = psetts$text.size,
        text.colour = psetts$text.colour,
        back.fill = psetts$background.colour
    ) +
    labs(
        x = NULL,
        y = NULL,
        title = "Northness! Northness!",
        subtitle = "*A suitable subtitle*<br>"
    ) -> northness
```

### Save
```{r}

ggsave(
    filename = "northness.png",
    plot = northness,
    path = dirs$figs,
    scale = 1,
    width = 13,
    height = 13,
    units = "cm",
    dpi = 350,
    limitsize = FALSE,
    bg = "transparent"
)
```

```{r}
# Add points to any of the plots above the usual way:
geom_point(
    data = nestbox_df, aes(
        x = x, y = y
    ),
    pch = 21, fill = "white",
    color = "#ffffff", alpha = 0.4, size = 0.1
)
```